---

- hosts: windows

  tasks:

#   INSTALL CHOCO

    - name: install_chocolatey

      win_chocolatey:

        name: chocolatey -y

        state: present

      ignore_errors: yes

#   INSTALL CHROME AND OTHER SOFTWARE

    - name: Installing Google Chrome

      win_chocolatey:

        name: googlechrome

        state: present

    - name: Installing FTP client FileZilla
     
      win_chocolatey:
        
        name: filezilla
       
        state: present

    - name: Installing database management tool
      win_chocolatey:
        name: dbeaver
        state: present

    - name: Adding a windows user for a client
      win_user:
        name: Worker
        password: "Password123"
        groups: ["Users"]
